### ISSUE TITLE
希望增加对第三方短信应用的支持

### ISSUE THREAD

**Issue by rhjdvsgsgks** [Kr328/nevo-decorators-sms-captchas#10]
使用 qksms 作为默认短信应用后，短信通知将不再由系统短信应用发出，希望能手动设置监听通知的应用

**Comment by rhjdvsgsgks** [comment]
辛苦了，`com.moez.QKSMS`
如果能手动让用户输入包名就更好了（不知道是不是很麻烦

**Comment by Kr328** [comment]
@rhjdvsgsgks 这样的话 不是麻烦 是 无法实现

**Comment by rhjdvsgsgks** [comment]
@Kr328 抱歉，我也不太懂，只是在 nevo-create new-skip-by active .n 的这个地方发现可以根据通知来进行某些修改（比如说 multi-line text ），可能这些是nevo自带的，单纯的nevo插件不能在这添加可修改的项

另外，您说的无法实现我猜可能是必须固定一个包名nevo才能在新增的时候提示可对指定包名的应用的通知进行修改，而这个包名除了hook或者自动重新生成（如gg的随机包名防检测）之外没法修改

我一开始想的是直接向nevo声明要所有应用的通知，然后到了此app里面再进行判定（如通过包名）是否为短信app，再对符合条件的app产生的通知进行处理

↑↑上面两段全是自己yy的，完全没有一点事实依据，让您见笑了

**Comment by Kr328** [comment]
@rhjdvsgsgks 模仿 Multi Line 的话 
对用户 不友好
要等到 有短信通知出现 才能添加

**Comment by rhjdvsgsgks** [comment]
@Kr328 也是诶，您看怎么方便怎么来吧
