### ISSUE TITLE
bug 蛮多

### ISSUE THREAD

**Issue by chochosan** [Kr328/nevo-decorators-sms-captchas#11]
1.最新版验证码消息闪一下就没了 退回旧版本没问题
2.复制验证码会闪退，且将默认动作设置为将短信设为已读无法实现。
设备：XZ1 Android 8.0 短信应用为 Google Android Message

**Comment by Kr328** [comment]
@chochosan 是有 bug 复制后删除 呢

**Comment by Kr328** [comment]
https://github.com/Kr328/nevo-decorators-sms-captchas/blob/develop/docs/obtain_permission.md

**Comment by chochosan** [comment]
这个权限给了

**Comment by Kr328** [comment]
@chochosan 删除呢 Google短信 确实不支持 标记已读

**Comment by chochosan** [comment]
现在的 bug 是来了短信闪一下就消失了

**Comment by Kr328** [comment]
@chochosan 1.7也有的话 估计就是你的ROM的问题了

**Comment by chochosan** [comment]
.*(澳[門门]|(赌|娱乐)场|(六合|博|时时)彩|百家乐|钱庄|办证|套牌|公关|黑车|投注|求子|彩[票金]|口子|少妇|女优|棋牌|配对成功).* //黄赌毒过滤
.*(交通|招商|光大|民生|浦发|人民|工商|农业|建设)银行.*(?<=(赠|微信|报名|参与|签约|满足)).* //银行活动过滤1
.*(?<=(赠|微信|报名|参与|签约|满足|券|奖)).*(交通|招商|光大|民生|浦发|人民|工商|农业|建设)银行.* //无匹配
.*((蚂蚁微|国信|微粒|有人|玖信|360)贷|(京东|小米)金融|考拉|分期乐).* //信贷全局
.*(交通|招商|光大|民生|浦发|人民|工商|农业|建设)银行.* //银行全局
.*(阿里|青|腾讯|又拍|七牛|华为|移动|金山|乐视|京东)云.* //云服务过滤
.*(获得|视频|爱心|客户端).*(移动|联通|电信|100(00|10|86)).*
.*(移动|联通|电信|100(00|10|86)).* //运营商全局
.*Q[Q群](?:.*[1-9][0-9]{4,10}).* //QQ广告过滤
.*((订购|登记|报名)|影视|沃视频).* //订阅过滤
.*(促销|优惠|大礼|开业|限量|签到|豪礼|礼品|来自|戳|提前[购抢]).* //活动过滤
.*打(\s*|\[|\]|\【|\】)开(\s*|\[|\]|\【|\】)手(\s*|\[|\]|\【|\】)机(\s*|\[|\]|\【|\】)[淘掏](\s*|\[|\]|\【|\】)宝.* //淘宝活动 感谢群友duck&@怕寂寞反馈
.*[送获].*额度.*[利日]息.*
.+恭喜.+回(复|短).+ //垃圾过滤
.*不(一定)?再有.*
.*公益短信.*
.*温馨提示.*
.*(退|回)(td|订).*

**Comment by Kr328** [comment]
@chochosan 震动是你的系统的问题 拦截短信没有API

**Comment by JO2EY** [comment]
之前和你说的 短信拦截 是指通过正则把某类信息处理为订阅类短信。你没能理解那就算了。
