### ISSUE TITLE
验证码误判

### ISSUE THREAD

**Issue by Trumeet** [Kr328/nevo-decorators-sms-captchas#16]
![screenshot_20181010-145530](https://user-images.githubusercontent.com/17158086/46768332-a6311880-cc9c-11e8-9f02-7d183c1986b1.png)

**Comment by Kr328** [comment]
@Trumeet 发原文 给我 试试  (

**Comment by Trumeet** [comment]
@Kr328
喵
```
为进一步保证信息及通信安全，Ping++ 将于 2018 年 11 月 13 日（周二）停止对 TLSv1.0、TLSv1.1 版本的支持，仅支持 TLSv1.2 及以上版本 。请通知贵司技术开发人员尽快完成相关验证并进行必要的升级，以免影响交易正常进行。详情请参考 ---> https://help.pingxx.com/article/1188106【简米网络】
```

**Comment by Kr328** [comment]
@Trumeet 试试 新 版本
被 Google 坑了 签名变了 
https://play.google.com/store/apps/details?id=me.kr328.nevo.decorators.smscaptcha

**Comment by dzshzx** [comment]
￼

不知道这算不算验证码误判？

**Comment by Kr328** [comment]
@dzshzx 惊了 (瑟瑟发抖.jpg
发下原文呗

**Comment by dzshzx** [comment]
【菜鸟驿站】您的申通包裹到中国传媒大学南广学院北服菜鸟驿站，请20:30前凭2413取，询15295785266

**Comment by Kr328** [comment]
> 【菜鸟驿站】您的申通包裹到中国传媒大学南广学院北服菜鸟驿站，请20:30前凭2413取，询15295785266

@dzshzx  新版本应该正常了
