### ISSUE TITLE
请求加入一个填写按钮

### ISSUE THREAD

**Issue by Ahua9527** [Kr328/nevo-decorators-sms-captchas#18]
一个按钮完成，复制粘贴两个步骤

**Comment by Kr328** [comment]
@Ahuababa 不是很明白

**Comment by Ahuababa** [comment]
在这里加一个功能  复制后粘贴

目前的情况是这样的，复制验证码后需要在输入栏长按再粘贴

我希望点完复制按钮后自动粘贴

大抵就是这样

**Comment by Ahuababa** [comment]
不能发图片，你点开复制后的操作就知道了

**Comment by Kr328** [comment]
@Ahuababa 很麻烦 我想想 (

**Comment by Kr328** [comment]
@Ahuababa 试试 测试版

**Comment by Ahua9527** [comment]
已测试，软键盘收起时不会出现ui。
没发现什么其他问题，其实你不用做ui啊。通知上不是有一个复制验证码按钮么,只要监控到点击复制按钮。就执行Ctrl+v命令...

**Comment by Kr328** [comment]
@Ahuababa 通知栏打开无障碍服务会失去焦点

**Comment by Kr328** [comment]
@Ahuababa 而且 软键盘收起消失 是 特性 (
