### ISSUE TITLE
对“第三方”短信应用的支持

### ISSUE THREAD

**Issue by yrccondor** [Kr328/nevo-decorators-sms-captchas#21]
我在使用从 Google Play 上下载的官方短信应用 `com.google.android.apps.messaging` ，发现通知没有被修改。是否是只支持系统短信应用 `com.android.messaging`？
按 #10 所说，是否可以内置一个常用短信应用的列表？这样至少可以覆盖到绝大部分场景。

**Comment by Kr328** [comment]
@yrccondor Google 短信 是 支持的
下一版本 将会可以请求为某个应用 启用

**Comment by yrccondor** [comment]
[![Screenshot_201901.png](https://i.loli.net/2019/01/13/5c3ad4edb5740.png)](https://i.loli.net/2019/01/13/5c3ad4edb5740.png)
不是很清楚原理，不过通知似乎没有走 Nevo（Outsider)
更多信息：版本 2.0，LOS 15.1(8.1)，Mi 5

**Comment by zhoukuncheng** [comment]
期待下个版本，我用三星自带信息
com.samsung.android.messaging
目前也没法使用Nevo

**Comment by Kr328** [comment]
@CeresCa @yrccondor 尝试 2.1.2

**Comment by yrccondor** [comment]
没有问题了😃
