### ISSUE TITLE
什么时候会更新

### ISSUE THREAD

**Issue by kaleai** [Kr328/nevo-decorators-sms-captchas#22]
现在的版本安装后无法替换短信的通知，并不知道怎么使用

**Comment by Kr328** [comment]
尝试 2.1.2 版本
附加到应用程序

**Comment by kaleai** [comment]
切到了那个分支，然后报错：

warn: removing resource me.kr328.nevo.decorators.smscaptcha:string/permission_tips_cancel without required default value.
warn: removing resource me.kr328.nevo.decorators.smscaptcha:string/permission_tips_content without required default value.
warn: removing resource me.kr328.nevo.decorators.smscaptcha:string/permission_tips_help without required default value.
D:\GithubProj\nevo-decorators-sms-captchas\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml:41: error: resource string/subscribe_service_description (aka me.kr328.nevo.decorators.smscaptcha:string/subscribe_service_description) not found.
D:\GithubProj\nevo-decorators-sms-captchas\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml:41: error: resource string/subscribe_service_name (aka me.kr328.nevo.decorators.smscaptcha:string/subscribe_service_name) not found.

![image](https://user-images.githubusercontent.com/9552155/54071875-d44b7080-42ad-11e9-8fab-9210a70a6e12.png)

应该是默认语言没有这个string，不知道是不是strings.xml里面没放的原因

**Comment by kaleai** [comment]
添加下面代码到strings.xml中后，减少了报错，但有两个异常仍旧无法解决。

<string name="permission_tips_content">因 Android 短信权限变动 需要额外操作授予写入权限</string>
    <string name="permission_tips_cancel">我已了解</string>
    <string name="permission_tips_help">查看帮助</string>

异常：

Android resource linking failed
D:\GithubProj\nevo-decorators-sms-captchas\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml:41: error: resource string/subscribe_service_description (aka me.kr328.nevo.decorators.smscaptcha:string/subscribe_service_description) not found.
D:\GithubProj\nevo-decorators-sms-captchas\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml:41: error: resource string/subscribe_service_name (aka me.kr328.nevo.decorators.smscaptcha:string/subscribe_service_name) not found.
error: failed processing manifest.

于是：添加了这两个string后，可以正常安装：

<string name="subscribe_service_description" translatable="false">subscribe_service_description</string>
<string name="subscribe_service_name" translatable="false">subscribe_service_name</string>

但安装后出现了找不到文件的异常：

![image](https://user-images.githubusercontent.com/9552155/54071926-9ef35280-42ae-11e9-82c0-6a061cb9eb24.png)

**Comment by Kr328** [comment]
@tianzhijiexian 请使用分支 develop-newsdk

**Comment by kaleai** [comment]
是develop-newsdk分支的代码
![image](https://user-images.githubusercontent.com/9552155/54080627-457f3800-432f-11e9-94a1-f2d919d6f06a.png)

**Comment by Kr328** [comment]
@tianzhijiexian 这个问题看起来是没有 clean

**Comment by kaleai** [comment]
clean后可以了，目前有如下三个问题：

1.可以自动复制验证码么？
2.在给了通知栏权限的前提下可以自动复制验证码后清除该条通知么？
3.在“附加到应用程序”这个应用列表中或许增加一个搜索栏会好一些

**Comment by Kr328** [comment]
@tianzhijiexian 1. 自动复制因为焦点等问题 现在仅提供辅助填充

**Comment by Kr328** [comment]
@tianzhijiexian 2.点了复制 或 辅助填充 会清除通知

**Comment by Kr328** [comment]
@tianzhijiexian 3. 不常用功能 感觉上不需要

**Comment by kaleai** [comment]
感谢回复
