### ISSUE TITLE
对自定义订阅正则屏蔽不起作用

### ISSUE THREAD

**Issue by TTTPOB** [Kr328/nevo-decorators-sms-captchas#24]
我的正则：
`.*(【|】|退订|TD|中国联通|宣).*`
短信内容：
中国联通我试一试能不能识别
自行测试结果：
![image](https://user-images.githubusercontent.com/19909103/59170197-1ff10d00-8b70-11e9-8863-1078056f6cdd.png)
但实际使用并不会对订阅短信做任何处理

**Comment by Kr328** [comment]
@TTTPOB 这个功能暂时被弃用 :(

**Comment by TTTPOB** [comment]
好的吧我觉得我还是比较需要的所以 [Feature request]! (
