### ISSUE TITLE
[feature request] 通过 F-Droid 发布

### ISSUE THREAD

**Issue by ivysrono** [Kr328/nevo-decorators-sms-captchas#26]
开源软件可以直接通过 F-Droid 自动编译发布。

https://f-droid.org/zh_Hans/contribute/

**Comment by Kr328** [comment]
@ivysrono 前提是不使用非 foss 库
然而 Google 的 库 基本上都不能符合

**Comment by ivysrono** [comment]
然后提交给了F-Droid第三方仓库，结果回应是一年没更新了……
https://gitlab.com/IzzyOnDroid/repo/issues/75
